// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: poses.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Polaris.Protobuf {

  /// <summary>Holder for reflection information generated from poses.proto</summary>
  public static partial class PosesReflection {

    #region Descriptor
    /// <summary>File descriptor for poses.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PosesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtwb3Nlcy5wcm90bxIFcG9zZXMiLQoKVmVjdG9yM0RUTxIJCgF4GAEgASgC",
            "EgkKAXkYAiABKAISCQoBehgDIAEoAiJRCgtLZXlmcmFtZURUTxIMCgR0aW1l",
            "GAEgASgCEg0KBXZhbHVlGAIgASgCEhEKCWluVGFuZ2VudBgDIAEoAhISCgpv",
            "dXRUYW5nZW50GAQgASgCIkEKEktleXBvaW50RXN0aW1hdGlvbhIJCgF4GGUg",
            "ASgCEgkKAXkYZiABKAISCQoBehhnIAEoAhIKCgFwGMkBIAEoAiJSChhLZXlw",
            "b2ludEVzdGltYXRpb25GcmFtZXMSCgoCaWQYZSABKAkSKgoGZnJhbWVzGMkB",
            "IAMoCzIZLnBvc2VzLktleXBvaW50RXN0aW1hdGlvbiJLChRQb3NlRXN0aW1h",
            "dGlvbkZyYW1lcxIzCglrZXlwb2ludHMYyQEgAygLMh8ucG9zZXMuS2V5cG9p",
            "bnRFc3RpbWF0aW9uRnJhbWVzIkwKFFBvc2VFc3RpbWF0aW9uUmVzdWx0EjQK",
            "D3Bvc2VFc3RpbWF0aW9ucxhlIAEoCzIbLnBvc2VzLlBvc2VFc3RpbWF0aW9u",
            "RnJhbWVzIk0KB01vdmVEVE8SMgoPdHJhbnNmb3JtQ3VydmVzGAEgAygLMhku",
            "cG9zZXMuVHJhbnNmb3JtQ3VydmVzRFRPEg4KBmxlbmd0aBgCIAEoAiKQAQoS",
            "VHJhbnNmb3JtQ3VydmVzRFRPEhUKDXRyYW5zZm9ybVBhdGgYASABKAkSLwoO",
            "cG9zaXRpb25DdXJ2ZXMYAiABKAsyFy5wb3Nlcy5WZWN0b3IzQ3VydmVzRFRP",
            "EjIKDnJvdGF0aW9uQ3VydmVzGAMgASgLMhoucG9zZXMuUXVhdGVybmlvbkN1",
            "cnZlc0RUTyJvChBWZWN0b3IzQ3VydmVzRFRPEh0KAXgYASADKAsyEi5wb3Nl",
            "cy5LZXlmcmFtZURUTxIdCgF5GAIgAygLMhIucG9zZXMuS2V5ZnJhbWVEVE8S",
            "HQoBehgDIAMoCzISLnBvc2VzLktleWZyYW1lRFRPIpEBChNRdWF0ZXJuaW9u",
            "Q3VydmVzRFRPEh0KAXgYASADKAsyEi5wb3Nlcy5LZXlmcmFtZURUTxIdCgF5",
            "GAIgAygLMhIucG9zZXMuS2V5ZnJhbWVEVE8SHQoBehgDIAMoCzISLnBvc2Vz",
            "LktleWZyYW1lRFRPEh0KAXcYBCADKAsyEi5wb3Nlcy5LZXlmcmFtZURUTyJp",
            "ChBUcmFuc2Zvcm1Qb3NlRFRPEhUKDXRyYW5zZm9ybVBhdGgYASABKAkSHgoD",
            "cG9zGAIgASgLMhEucG9zZXMuVmVjdG9yM0RUTxIeCgNyb3QYAyABKAsyES5w",
            "b3Nlcy5WZWN0b3IzRFRPIjYKB1Bvc2VEVE8SKwoKdHJhbnNmb3JtcxgBIAMo",
            "CzIXLnBvc2VzLlRyYW5zZm9ybVBvc2VEVE8iVAoRQW5pbWF0YWJsZVBvc2VE",
            "VE8SHQoFYm9uZXMYASABKAsyDi5wb3Nlcy5Qb3NlRFRPEiAKCGNvbnRyb2xz",
            "GAIgASgLMg4ucG9zZXMuUG9zZURUTyJAChFFZGl0b3JNb3ZlUG9zZURUTxIN",
            "CgVmcmFtZRgBIAEoBRIcCgRwb3NlGAIgASgLMg4ucG9zZXMuUG9zZURUTyJB",
            "ChFFZGl0b3JNb3ZlTWV0YURUTxIXCg9mcmFtZXNQZXJTZWNvbmQYASABKAUS",
            "EwoLZnJhbWVzVG90YWwYAiABKAUiZAoNRWRpdG9yTW92ZURUTxIqCghtZXRh",
            "ZGF0YRgBIAEoCzIYLnBvc2VzLkVkaXRvck1vdmVNZXRhRFRPEicKBXBvc2Vz",
            "GAIgAygLMhgucG9zZXMuRWRpdG9yTW92ZVBvc2VEVE9CE6oCEFBvbGFyaXMu",
            "UHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.Vector3DTO), global::Polaris.Protobuf.Vector3DTO.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.KeyframeDTO), global::Polaris.Protobuf.KeyframeDTO.Parser, new[]{ "Time", "Value", "InTangent", "OutTangent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.KeypointEstimation), global::Polaris.Protobuf.KeypointEstimation.Parser, new[]{ "X", "Y", "Z", "P" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.KeypointEstimationFrames), global::Polaris.Protobuf.KeypointEstimationFrames.Parser, new[]{ "Id", "Frames" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.PoseEstimationFrames), global::Polaris.Protobuf.PoseEstimationFrames.Parser, new[]{ "Keypoints" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.PoseEstimationResult), global::Polaris.Protobuf.PoseEstimationResult.Parser, new[]{ "PoseEstimations" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.MoveDTO), global::Polaris.Protobuf.MoveDTO.Parser, new[]{ "TransformCurves", "Length" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.TransformCurvesDTO), global::Polaris.Protobuf.TransformCurvesDTO.Parser, new[]{ "TransformPath", "PositionCurves", "RotationCurves" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.Vector3CurvesDTO), global::Polaris.Protobuf.Vector3CurvesDTO.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.QuaternionCurvesDTO), global::Polaris.Protobuf.QuaternionCurvesDTO.Parser, new[]{ "X", "Y", "Z", "W" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.TransformPoseDTO), global::Polaris.Protobuf.TransformPoseDTO.Parser, new[]{ "TransformPath", "Pos", "Rot" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.PoseDTO), global::Polaris.Protobuf.PoseDTO.Parser, new[]{ "Transforms" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.AnimatablePoseDTO), global::Polaris.Protobuf.AnimatablePoseDTO.Parser, new[]{ "Bones", "Controls" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.EditorMovePoseDTO), global::Polaris.Protobuf.EditorMovePoseDTO.Parser, new[]{ "Frame", "Pose" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.EditorMoveMetaDTO), global::Polaris.Protobuf.EditorMoveMetaDTO.Parser, new[]{ "FramesPerSecond", "FramesTotal" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Polaris.Protobuf.EditorMoveDTO), global::Polaris.Protobuf.EditorMoveDTO.Parser, new[]{ "Metadata", "Poses" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Vector3DTO : pb::IMessage<Vector3DTO> {
    private static readonly pb::MessageParser<Vector3DTO> _parser = new pb::MessageParser<Vector3DTO>(() => new Vector3DTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vector3DTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3DTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3DTO(Vector3DTO other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3DTO Clone() {
      return new Vector3DTO(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Vector3DTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vector3DTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vector3DTO other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class KeyframeDTO : pb::IMessage<KeyframeDTO> {
    private static readonly pb::MessageParser<KeyframeDTO> _parser = new pb::MessageParser<KeyframeDTO>(() => new KeyframeDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KeyframeDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyframeDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyframeDTO(KeyframeDTO other) : this() {
      time_ = other.time_;
      value_ = other.value_;
      inTangent_ = other.inTangent_;
      outTangent_ = other.outTangent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyframeDTO Clone() {
      return new KeyframeDTO(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private float time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private float value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "inTangent" field.</summary>
    public const int InTangentFieldNumber = 3;
    private float inTangent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float InTangent {
      get { return inTangent_; }
      set {
        inTangent_ = value;
      }
    }

    /// <summary>Field number for the "outTangent" field.</summary>
    public const int OutTangentFieldNumber = 4;
    private float outTangent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float OutTangent {
      get { return outTangent_; }
      set {
        outTangent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KeyframeDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KeyframeDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Time, other.Time)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value, other.Value)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(InTangent, other.InTangent)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(OutTangent, other.OutTangent)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Time != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Time);
      if (Value != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value);
      if (InTangent != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(InTangent);
      if (OutTangent != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(OutTangent);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Time != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Time);
      }
      if (Value != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Value);
      }
      if (InTangent != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(InTangent);
      }
      if (OutTangent != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(OutTangent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Time != 0F) {
        size += 1 + 4;
      }
      if (Value != 0F) {
        size += 1 + 4;
      }
      if (InTangent != 0F) {
        size += 1 + 4;
      }
      if (OutTangent != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KeyframeDTO other) {
      if (other == null) {
        return;
      }
      if (other.Time != 0F) {
        Time = other.Time;
      }
      if (other.Value != 0F) {
        Value = other.Value;
      }
      if (other.InTangent != 0F) {
        InTangent = other.InTangent;
      }
      if (other.OutTangent != 0F) {
        OutTangent = other.OutTangent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Time = input.ReadFloat();
            break;
          }
          case 21: {
            Value = input.ReadFloat();
            break;
          }
          case 29: {
            InTangent = input.ReadFloat();
            break;
          }
          case 37: {
            OutTangent = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class KeypointEstimation : pb::IMessage<KeypointEstimation> {
    private static readonly pb::MessageParser<KeypointEstimation> _parser = new pb::MessageParser<KeypointEstimation>(() => new KeypointEstimation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KeypointEstimation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeypointEstimation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeypointEstimation(KeypointEstimation other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      p_ = other.p_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeypointEstimation Clone() {
      return new KeypointEstimation(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 101;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 102;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 103;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "p" field.</summary>
    public const int PFieldNumber = 201;
    private float p_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float P {
      get { return p_; }
      set {
        p_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KeypointEstimation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KeypointEstimation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(P, other.P)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (P != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(P);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(173, 6);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(181, 6);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(189, 6);
        output.WriteFloat(Z);
      }
      if (P != 0F) {
        output.WriteRawTag(205, 12);
        output.WriteFloat(P);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 2 + 4;
      }
      if (Y != 0F) {
        size += 2 + 4;
      }
      if (Z != 0F) {
        size += 2 + 4;
      }
      if (P != 0F) {
        size += 2 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KeypointEstimation other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.P != 0F) {
        P = other.P;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 813: {
            X = input.ReadFloat();
            break;
          }
          case 821: {
            Y = input.ReadFloat();
            break;
          }
          case 829: {
            Z = input.ReadFloat();
            break;
          }
          case 1613: {
            P = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class KeypointEstimationFrames : pb::IMessage<KeypointEstimationFrames> {
    private static readonly pb::MessageParser<KeypointEstimationFrames> _parser = new pb::MessageParser<KeypointEstimationFrames>(() => new KeypointEstimationFrames());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KeypointEstimationFrames> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeypointEstimationFrames() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeypointEstimationFrames(KeypointEstimationFrames other) : this() {
      id_ = other.id_;
      frames_ = other.frames_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeypointEstimationFrames Clone() {
      return new KeypointEstimationFrames(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 101;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "frames" field.</summary>
    public const int FramesFieldNumber = 201;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeypointEstimation> _repeated_frames_codec
        = pb::FieldCodec.ForMessage(1610, global::Polaris.Protobuf.KeypointEstimation.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeypointEstimation> frames_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeypointEstimation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeypointEstimation> Frames {
      get { return frames_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KeypointEstimationFrames);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KeypointEstimationFrames other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!frames_.Equals(other.frames_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= frames_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(170, 6);
        output.WriteString(Id);
      }
      frames_.WriteTo(output, _repeated_frames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += frames_.CalculateSize(_repeated_frames_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KeypointEstimationFrames other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      frames_.Add(other.frames_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 810: {
            Id = input.ReadString();
            break;
          }
          case 1610: {
            frames_.AddEntriesFrom(input, _repeated_frames_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PoseEstimationFrames : pb::IMessage<PoseEstimationFrames> {
    private static readonly pb::MessageParser<PoseEstimationFrames> _parser = new pb::MessageParser<PoseEstimationFrames>(() => new PoseEstimationFrames());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PoseEstimationFrames> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseEstimationFrames() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseEstimationFrames(PoseEstimationFrames other) : this() {
      keypoints_ = other.keypoints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseEstimationFrames Clone() {
      return new PoseEstimationFrames(this);
    }

    /// <summary>Field number for the "keypoints" field.</summary>
    public const int KeypointsFieldNumber = 201;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeypointEstimationFrames> _repeated_keypoints_codec
        = pb::FieldCodec.ForMessage(1610, global::Polaris.Protobuf.KeypointEstimationFrames.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeypointEstimationFrames> keypoints_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeypointEstimationFrames>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeypointEstimationFrames> Keypoints {
      get { return keypoints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PoseEstimationFrames);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PoseEstimationFrames other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!keypoints_.Equals(other.keypoints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= keypoints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      keypoints_.WriteTo(output, _repeated_keypoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += keypoints_.CalculateSize(_repeated_keypoints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PoseEstimationFrames other) {
      if (other == null) {
        return;
      }
      keypoints_.Add(other.keypoints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 1610: {
            keypoints_.AddEntriesFrom(input, _repeated_keypoints_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PoseEstimationResult : pb::IMessage<PoseEstimationResult> {
    private static readonly pb::MessageParser<PoseEstimationResult> _parser = new pb::MessageParser<PoseEstimationResult>(() => new PoseEstimationResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PoseEstimationResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseEstimationResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseEstimationResult(PoseEstimationResult other) : this() {
      poseEstimations_ = other.poseEstimations_ != null ? other.poseEstimations_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseEstimationResult Clone() {
      return new PoseEstimationResult(this);
    }

    /// <summary>Field number for the "poseEstimations" field.</summary>
    public const int PoseEstimationsFieldNumber = 101;
    private global::Polaris.Protobuf.PoseEstimationFrames poseEstimations_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.PoseEstimationFrames PoseEstimations {
      get { return poseEstimations_; }
      set {
        poseEstimations_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PoseEstimationResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PoseEstimationResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PoseEstimations, other.PoseEstimations)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (poseEstimations_ != null) hash ^= PoseEstimations.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (poseEstimations_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(PoseEstimations);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (poseEstimations_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PoseEstimations);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PoseEstimationResult other) {
      if (other == null) {
        return;
      }
      if (other.poseEstimations_ != null) {
        if (poseEstimations_ == null) {
          PoseEstimations = new global::Polaris.Protobuf.PoseEstimationFrames();
        }
        PoseEstimations.MergeFrom(other.PoseEstimations);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 810: {
            if (poseEstimations_ == null) {
              PoseEstimations = new global::Polaris.Protobuf.PoseEstimationFrames();
            }
            input.ReadMessage(PoseEstimations);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MoveDTO : pb::IMessage<MoveDTO> {
    private static readonly pb::MessageParser<MoveDTO> _parser = new pb::MessageParser<MoveDTO>(() => new MoveDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MoveDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveDTO(MoveDTO other) : this() {
      transformCurves_ = other.transformCurves_.Clone();
      length_ = other.length_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveDTO Clone() {
      return new MoveDTO(this);
    }

    /// <summary>Field number for the "transformCurves" field.</summary>
    public const int TransformCurvesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.TransformCurvesDTO> _repeated_transformCurves_codec
        = pb::FieldCodec.ForMessage(10, global::Polaris.Protobuf.TransformCurvesDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.TransformCurvesDTO> transformCurves_ = new pbc::RepeatedField<global::Polaris.Protobuf.TransformCurvesDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.TransformCurvesDTO> TransformCurves {
      get { return transformCurves_; }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 2;
    private float length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MoveDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MoveDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!transformCurves_.Equals(other.transformCurves_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Length, other.Length)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= transformCurves_.GetHashCode();
      if (Length != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Length);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      transformCurves_.WriteTo(output, _repeated_transformCurves_codec);
      if (Length != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += transformCurves_.CalculateSize(_repeated_transformCurves_codec);
      if (Length != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MoveDTO other) {
      if (other == null) {
        return;
      }
      transformCurves_.Add(other.transformCurves_);
      if (other.Length != 0F) {
        Length = other.Length;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            transformCurves_.AddEntriesFrom(input, _repeated_transformCurves_codec);
            break;
          }
          case 21: {
            Length = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TransformCurvesDTO : pb::IMessage<TransformCurvesDTO> {
    private static readonly pb::MessageParser<TransformCurvesDTO> _parser = new pb::MessageParser<TransformCurvesDTO>(() => new TransformCurvesDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransformCurvesDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformCurvesDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformCurvesDTO(TransformCurvesDTO other) : this() {
      transformPath_ = other.transformPath_;
      positionCurves_ = other.positionCurves_ != null ? other.positionCurves_.Clone() : null;
      rotationCurves_ = other.rotationCurves_ != null ? other.rotationCurves_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformCurvesDTO Clone() {
      return new TransformCurvesDTO(this);
    }

    /// <summary>Field number for the "transformPath" field.</summary>
    public const int TransformPathFieldNumber = 1;
    private string transformPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TransformPath {
      get { return transformPath_; }
      set {
        transformPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "positionCurves" field.</summary>
    public const int PositionCurvesFieldNumber = 2;
    private global::Polaris.Protobuf.Vector3CurvesDTO positionCurves_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.Vector3CurvesDTO PositionCurves {
      get { return positionCurves_; }
      set {
        positionCurves_ = value;
      }
    }

    /// <summary>Field number for the "rotationCurves" field.</summary>
    public const int RotationCurvesFieldNumber = 3;
    private global::Polaris.Protobuf.QuaternionCurvesDTO rotationCurves_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.QuaternionCurvesDTO RotationCurves {
      get { return rotationCurves_; }
      set {
        rotationCurves_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransformCurvesDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransformCurvesDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TransformPath != other.TransformPath) return false;
      if (!object.Equals(PositionCurves, other.PositionCurves)) return false;
      if (!object.Equals(RotationCurves, other.RotationCurves)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TransformPath.Length != 0) hash ^= TransformPath.GetHashCode();
      if (positionCurves_ != null) hash ^= PositionCurves.GetHashCode();
      if (rotationCurves_ != null) hash ^= RotationCurves.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TransformPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TransformPath);
      }
      if (positionCurves_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PositionCurves);
      }
      if (rotationCurves_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RotationCurves);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TransformPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransformPath);
      }
      if (positionCurves_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PositionCurves);
      }
      if (rotationCurves_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RotationCurves);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransformCurvesDTO other) {
      if (other == null) {
        return;
      }
      if (other.TransformPath.Length != 0) {
        TransformPath = other.TransformPath;
      }
      if (other.positionCurves_ != null) {
        if (positionCurves_ == null) {
          PositionCurves = new global::Polaris.Protobuf.Vector3CurvesDTO();
        }
        PositionCurves.MergeFrom(other.PositionCurves);
      }
      if (other.rotationCurves_ != null) {
        if (rotationCurves_ == null) {
          RotationCurves = new global::Polaris.Protobuf.QuaternionCurvesDTO();
        }
        RotationCurves.MergeFrom(other.RotationCurves);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TransformPath = input.ReadString();
            break;
          }
          case 18: {
            if (positionCurves_ == null) {
              PositionCurves = new global::Polaris.Protobuf.Vector3CurvesDTO();
            }
            input.ReadMessage(PositionCurves);
            break;
          }
          case 26: {
            if (rotationCurves_ == null) {
              RotationCurves = new global::Polaris.Protobuf.QuaternionCurvesDTO();
            }
            input.ReadMessage(RotationCurves);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Vector3CurvesDTO : pb::IMessage<Vector3CurvesDTO> {
    private static readonly pb::MessageParser<Vector3CurvesDTO> _parser = new pb::MessageParser<Vector3CurvesDTO>(() => new Vector3CurvesDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vector3CurvesDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3CurvesDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3CurvesDTO(Vector3CurvesDTO other) : this() {
      x_ = other.x_.Clone();
      y_ = other.y_.Clone();
      z_ = other.z_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3CurvesDTO Clone() {
      return new Vector3CurvesDTO(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_x_codec
        = pb::FieldCodec.ForMessage(10, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> x_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> X {
      get { return x_; }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_y_codec
        = pb::FieldCodec.ForMessage(18, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> y_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> Y {
      get { return y_; }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_z_codec
        = pb::FieldCodec.ForMessage(26, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> z_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> Z {
      get { return z_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Vector3CurvesDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vector3CurvesDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!x_.Equals(other.x_)) return false;
      if(!y_.Equals(other.y_)) return false;
      if(!z_.Equals(other.z_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= x_.GetHashCode();
      hash ^= y_.GetHashCode();
      hash ^= z_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      x_.WriteTo(output, _repeated_x_codec);
      y_.WriteTo(output, _repeated_y_codec);
      z_.WriteTo(output, _repeated_z_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += x_.CalculateSize(_repeated_x_codec);
      size += y_.CalculateSize(_repeated_y_codec);
      size += z_.CalculateSize(_repeated_z_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vector3CurvesDTO other) {
      if (other == null) {
        return;
      }
      x_.Add(other.x_);
      y_.Add(other.y_);
      z_.Add(other.z_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            x_.AddEntriesFrom(input, _repeated_x_codec);
            break;
          }
          case 18: {
            y_.AddEntriesFrom(input, _repeated_y_codec);
            break;
          }
          case 26: {
            z_.AddEntriesFrom(input, _repeated_z_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class QuaternionCurvesDTO : pb::IMessage<QuaternionCurvesDTO> {
    private static readonly pb::MessageParser<QuaternionCurvesDTO> _parser = new pb::MessageParser<QuaternionCurvesDTO>(() => new QuaternionCurvesDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuaternionCurvesDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuaternionCurvesDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuaternionCurvesDTO(QuaternionCurvesDTO other) : this() {
      x_ = other.x_.Clone();
      y_ = other.y_.Clone();
      z_ = other.z_.Clone();
      w_ = other.w_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuaternionCurvesDTO Clone() {
      return new QuaternionCurvesDTO(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_x_codec
        = pb::FieldCodec.ForMessage(10, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> x_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> X {
      get { return x_; }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_y_codec
        = pb::FieldCodec.ForMessage(18, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> y_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> Y {
      get { return y_; }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_z_codec
        = pb::FieldCodec.ForMessage(26, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> z_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> Z {
      get { return z_; }
    }

    /// <summary>Field number for the "w" field.</summary>
    public const int WFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.KeyframeDTO> _repeated_w_codec
        = pb::FieldCodec.ForMessage(34, global::Polaris.Protobuf.KeyframeDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> w_ = new pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.KeyframeDTO> W {
      get { return w_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuaternionCurvesDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuaternionCurvesDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!x_.Equals(other.x_)) return false;
      if(!y_.Equals(other.y_)) return false;
      if(!z_.Equals(other.z_)) return false;
      if(!w_.Equals(other.w_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= x_.GetHashCode();
      hash ^= y_.GetHashCode();
      hash ^= z_.GetHashCode();
      hash ^= w_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      x_.WriteTo(output, _repeated_x_codec);
      y_.WriteTo(output, _repeated_y_codec);
      z_.WriteTo(output, _repeated_z_codec);
      w_.WriteTo(output, _repeated_w_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += x_.CalculateSize(_repeated_x_codec);
      size += y_.CalculateSize(_repeated_y_codec);
      size += z_.CalculateSize(_repeated_z_codec);
      size += w_.CalculateSize(_repeated_w_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuaternionCurvesDTO other) {
      if (other == null) {
        return;
      }
      x_.Add(other.x_);
      y_.Add(other.y_);
      z_.Add(other.z_);
      w_.Add(other.w_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            x_.AddEntriesFrom(input, _repeated_x_codec);
            break;
          }
          case 18: {
            y_.AddEntriesFrom(input, _repeated_y_codec);
            break;
          }
          case 26: {
            z_.AddEntriesFrom(input, _repeated_z_codec);
            break;
          }
          case 34: {
            w_.AddEntriesFrom(input, _repeated_w_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class TransformPoseDTO : pb::IMessage<TransformPoseDTO> {
    private static readonly pb::MessageParser<TransformPoseDTO> _parser = new pb::MessageParser<TransformPoseDTO>(() => new TransformPoseDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransformPoseDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformPoseDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformPoseDTO(TransformPoseDTO other) : this() {
      transformPath_ = other.transformPath_;
      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
      rot_ = other.rot_ != null ? other.rot_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformPoseDTO Clone() {
      return new TransformPoseDTO(this);
    }

    /// <summary>Field number for the "transformPath" field.</summary>
    public const int TransformPathFieldNumber = 1;
    private string transformPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TransformPath {
      get { return transformPath_; }
      set {
        transformPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 2;
    private global::Polaris.Protobuf.Vector3DTO pos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.Vector3DTO Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    /// <summary>Field number for the "rot" field.</summary>
    public const int RotFieldNumber = 3;
    private global::Polaris.Protobuf.Vector3DTO rot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.Vector3DTO Rot {
      get { return rot_; }
      set {
        rot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransformPoseDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransformPoseDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TransformPath != other.TransformPath) return false;
      if (!object.Equals(Pos, other.Pos)) return false;
      if (!object.Equals(Rot, other.Rot)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TransformPath.Length != 0) hash ^= TransformPath.GetHashCode();
      if (pos_ != null) hash ^= Pos.GetHashCode();
      if (rot_ != null) hash ^= Rot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TransformPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TransformPath);
      }
      if (pos_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pos);
      }
      if (rot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TransformPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransformPath);
      }
      if (pos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
      }
      if (rot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransformPoseDTO other) {
      if (other == null) {
        return;
      }
      if (other.TransformPath.Length != 0) {
        TransformPath = other.TransformPath;
      }
      if (other.pos_ != null) {
        if (pos_ == null) {
          Pos = new global::Polaris.Protobuf.Vector3DTO();
        }
        Pos.MergeFrom(other.Pos);
      }
      if (other.rot_ != null) {
        if (rot_ == null) {
          Rot = new global::Polaris.Protobuf.Vector3DTO();
        }
        Rot.MergeFrom(other.Rot);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TransformPath = input.ReadString();
            break;
          }
          case 18: {
            if (pos_ == null) {
              Pos = new global::Polaris.Protobuf.Vector3DTO();
            }
            input.ReadMessage(Pos);
            break;
          }
          case 26: {
            if (rot_ == null) {
              Rot = new global::Polaris.Protobuf.Vector3DTO();
            }
            input.ReadMessage(Rot);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PoseDTO : pb::IMessage<PoseDTO> {
    private static readonly pb::MessageParser<PoseDTO> _parser = new pb::MessageParser<PoseDTO>(() => new PoseDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PoseDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseDTO(PoseDTO other) : this() {
      transforms_ = other.transforms_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoseDTO Clone() {
      return new PoseDTO(this);
    }

    /// <summary>Field number for the "transforms" field.</summary>
    public const int TransformsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.TransformPoseDTO> _repeated_transforms_codec
        = pb::FieldCodec.ForMessage(10, global::Polaris.Protobuf.TransformPoseDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.TransformPoseDTO> transforms_ = new pbc::RepeatedField<global::Polaris.Protobuf.TransformPoseDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.TransformPoseDTO> Transforms {
      get { return transforms_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PoseDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PoseDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!transforms_.Equals(other.transforms_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= transforms_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      transforms_.WriteTo(output, _repeated_transforms_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += transforms_.CalculateSize(_repeated_transforms_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PoseDTO other) {
      if (other == null) {
        return;
      }
      transforms_.Add(other.transforms_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            transforms_.AddEntriesFrom(input, _repeated_transforms_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class AnimatablePoseDTO : pb::IMessage<AnimatablePoseDTO> {
    private static readonly pb::MessageParser<AnimatablePoseDTO> _parser = new pb::MessageParser<AnimatablePoseDTO>(() => new AnimatablePoseDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnimatablePoseDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnimatablePoseDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnimatablePoseDTO(AnimatablePoseDTO other) : this() {
      bones_ = other.bones_ != null ? other.bones_.Clone() : null;
      controls_ = other.controls_ != null ? other.controls_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnimatablePoseDTO Clone() {
      return new AnimatablePoseDTO(this);
    }

    /// <summary>Field number for the "bones" field.</summary>
    public const int BonesFieldNumber = 1;
    private global::Polaris.Protobuf.PoseDTO bones_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.PoseDTO Bones {
      get { return bones_; }
      set {
        bones_ = value;
      }
    }

    /// <summary>Field number for the "controls" field.</summary>
    public const int ControlsFieldNumber = 2;
    private global::Polaris.Protobuf.PoseDTO controls_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.PoseDTO Controls {
      get { return controls_; }
      set {
        controls_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnimatablePoseDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnimatablePoseDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Bones, other.Bones)) return false;
      if (!object.Equals(Controls, other.Controls)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (bones_ != null) hash ^= Bones.GetHashCode();
      if (controls_ != null) hash ^= Controls.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (bones_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Bones);
      }
      if (controls_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Controls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (bones_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bones);
      }
      if (controls_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Controls);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnimatablePoseDTO other) {
      if (other == null) {
        return;
      }
      if (other.bones_ != null) {
        if (bones_ == null) {
          Bones = new global::Polaris.Protobuf.PoseDTO();
        }
        Bones.MergeFrom(other.Bones);
      }
      if (other.controls_ != null) {
        if (controls_ == null) {
          Controls = new global::Polaris.Protobuf.PoseDTO();
        }
        Controls.MergeFrom(other.Controls);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (bones_ == null) {
              Bones = new global::Polaris.Protobuf.PoseDTO();
            }
            input.ReadMessage(Bones);
            break;
          }
          case 18: {
            if (controls_ == null) {
              Controls = new global::Polaris.Protobuf.PoseDTO();
            }
            input.ReadMessage(Controls);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EditorMovePoseDTO : pb::IMessage<EditorMovePoseDTO> {
    private static readonly pb::MessageParser<EditorMovePoseDTO> _parser = new pb::MessageParser<EditorMovePoseDTO>(() => new EditorMovePoseDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditorMovePoseDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMovePoseDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMovePoseDTO(EditorMovePoseDTO other) : this() {
      frame_ = other.frame_;
      pose_ = other.pose_ != null ? other.pose_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMovePoseDTO Clone() {
      return new EditorMovePoseDTO(this);
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 1;
    private int frame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Frame {
      get { return frame_; }
      set {
        frame_ = value;
      }
    }

    /// <summary>Field number for the "pose" field.</summary>
    public const int PoseFieldNumber = 2;
    private global::Polaris.Protobuf.PoseDTO pose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.PoseDTO Pose {
      get { return pose_; }
      set {
        pose_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditorMovePoseDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditorMovePoseDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Frame != other.Frame) return false;
      if (!object.Equals(Pose, other.Pose)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Frame != 0) hash ^= Frame.GetHashCode();
      if (pose_ != null) hash ^= Pose.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (pose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Frame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Frame);
      }
      if (pose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pose);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditorMovePoseDTO other) {
      if (other == null) {
        return;
      }
      if (other.Frame != 0) {
        Frame = other.Frame;
      }
      if (other.pose_ != null) {
        if (pose_ == null) {
          Pose = new global::Polaris.Protobuf.PoseDTO();
        }
        Pose.MergeFrom(other.Pose);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 18: {
            if (pose_ == null) {
              Pose = new global::Polaris.Protobuf.PoseDTO();
            }
            input.ReadMessage(Pose);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EditorMoveMetaDTO : pb::IMessage<EditorMoveMetaDTO> {
    private static readonly pb::MessageParser<EditorMoveMetaDTO> _parser = new pb::MessageParser<EditorMoveMetaDTO>(() => new EditorMoveMetaDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditorMoveMetaDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMoveMetaDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMoveMetaDTO(EditorMoveMetaDTO other) : this() {
      framesPerSecond_ = other.framesPerSecond_;
      framesTotal_ = other.framesTotal_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMoveMetaDTO Clone() {
      return new EditorMoveMetaDTO(this);
    }

    /// <summary>Field number for the "framesPerSecond" field.</summary>
    public const int FramesPerSecondFieldNumber = 1;
    private int framesPerSecond_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FramesPerSecond {
      get { return framesPerSecond_; }
      set {
        framesPerSecond_ = value;
      }
    }

    /// <summary>Field number for the "framesTotal" field.</summary>
    public const int FramesTotalFieldNumber = 2;
    private int framesTotal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FramesTotal {
      get { return framesTotal_; }
      set {
        framesTotal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditorMoveMetaDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditorMoveMetaDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FramesPerSecond != other.FramesPerSecond) return false;
      if (FramesTotal != other.FramesTotal) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FramesPerSecond != 0) hash ^= FramesPerSecond.GetHashCode();
      if (FramesTotal != 0) hash ^= FramesTotal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FramesPerSecond != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FramesPerSecond);
      }
      if (FramesTotal != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FramesTotal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FramesPerSecond != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FramesPerSecond);
      }
      if (FramesTotal != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FramesTotal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditorMoveMetaDTO other) {
      if (other == null) {
        return;
      }
      if (other.FramesPerSecond != 0) {
        FramesPerSecond = other.FramesPerSecond;
      }
      if (other.FramesTotal != 0) {
        FramesTotal = other.FramesTotal;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FramesPerSecond = input.ReadInt32();
            break;
          }
          case 16: {
            FramesTotal = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EditorMoveDTO : pb::IMessage<EditorMoveDTO> {
    private static readonly pb::MessageParser<EditorMoveDTO> _parser = new pb::MessageParser<EditorMoveDTO>(() => new EditorMoveDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditorMoveDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Polaris.Protobuf.PosesReflection.Descriptor.MessageTypes[15]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMoveDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMoveDTO(EditorMoveDTO other) : this() {
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      poses_ = other.poses_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditorMoveDTO Clone() {
      return new EditorMoveDTO(this);
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 1;
    private global::Polaris.Protobuf.EditorMoveMetaDTO metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Polaris.Protobuf.EditorMoveMetaDTO Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "poses" field.</summary>
    public const int PosesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Polaris.Protobuf.EditorMovePoseDTO> _repeated_poses_codec
        = pb::FieldCodec.ForMessage(18, global::Polaris.Protobuf.EditorMovePoseDTO.Parser);
    private readonly pbc::RepeatedField<global::Polaris.Protobuf.EditorMovePoseDTO> poses_ = new pbc::RepeatedField<global::Polaris.Protobuf.EditorMovePoseDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Polaris.Protobuf.EditorMovePoseDTO> Poses {
      get { return poses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditorMoveDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditorMoveDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if(!poses_.Equals(other.poses_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      hash ^= poses_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (metadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Metadata);
      }
      poses_.WriteTo(output, _repeated_poses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      size += poses_.CalculateSize(_repeated_poses_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditorMoveDTO other) {
      if (other == null) {
        return;
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::Polaris.Protobuf.EditorMoveMetaDTO();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      poses_.Add(other.poses_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (metadata_ == null) {
              Metadata = new global::Polaris.Protobuf.EditorMoveMetaDTO();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 18: {
            poses_.AddEntriesFrom(input, _repeated_poses_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
